server:
  port: 3041
circle:
  apiKey: 'TEST_API_KEY:3710354139bba9490dbf27102da20363:744e55937ca44b1537010d5e1c4cbe54'
  app_id: '9554667d-e16a-5a9d-bf88-ee0648034a49'
  ENTITY_SECRET: '3f64e44eb9287305e9ea0c84caccf7e76cbe7f212871c17879950f6a3ccbd105'
  ENCRYPTED_DATA: 'YWYOzjbnNi6TdAKcNzJKjdIaA2gdm31HHa+dZ7/LCZeSqr9IUtgGyBExcfUMmBjjNSzUtB/LDfOmqdUL5IziW00M/GVxXXL/s3sjAwH1k336jdJuBGsG11QpS+vjxqUjZTSx/MRjSpKuvHgBTp3F5oa82kRu59ghrXGkPxK2VMYMx5E5T+Dy4SE50lwbc6ImWb9DorfuX8uudjl7Z7+dQidCeONHeCgN76EjWlZX7oiIouku2MSHhnOmKOMN78s+Ul7/lQ1Gxn9BWV1Burh1ra4TW+D0ulvztnyTlvde2EjLxIm5pEazaFIR+QKo6hDR0EonnCKxAHSnsEmjZ6MR1KgabumsI8B+1RuJ7Vka5u7g0WA7YFGNBac/R1sBo9V6xsDIqHgoWEVjyekJvrbikzWwH6A2VefrTuzJfABfvVUL8lRjsglm4flrwGJGo8q2pDL11E9t4TfU53ul8jIkB5FtxSEWZWzbWyiO8C1Nhyhhp4Zt+XYpi8PAhEyKKEeosgcUtTBLEuZlU3g4952F6LiLqZuhu+O6TMZx5TR6focX9FvFO+rEoQw+ZbU09ZFmA95xZB2jXww5Q7MLiwrkccwYJcM2a1MJFUG53APLWaJA6KRagRVGXXYHdtDcf6rRKUhDriOImAYXmJvcsfATqTnRML3y3cDr03aQlvFdEhU='
  WALLET_SET_ID: '45afbcb8-b96b-5f37-91d5-6141192f7a32'
db:
  type: 'postgres'
  host: 'localhost'
  username: 'postgres'
  password: '1950'
  database: 'circle_backend_service'
  synchronize: true
  schema: 'public'
  charset: 'UTF8_GENERAL_CI'
  port: 5432

jwt:
  secret: 'YnsErysy*@455HfgfFGF445667SSDS2342323DFDFDFe3543cvcdfd@@!!weTT5%&&FFHvvdd*Brs49'
  expire: 600000
